name: Teste Container
on: 
    workflow_dispatch:  
jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - name: execucao do runner
              run: cat /etc/os-release
            - name: execucao do container
              uses: docker://alpine:latest
              with:
                  entrypoint: cat
                  args: /etc/os-release
